name: Build and Deploy Docker to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-app .

      # Run Docker container
      - name: Run Docker container
        run: docker run --name my-app-container -d my-app

      # Copy the build output from the Docker container
      - name: Copy build output
        run: docker cp my-app-container:/app/dist ./dist

      # Stop and remove the Docker container
      - name: Stop and remove container
        run: |
          docker stop my-app-container
          docker rm my-app-container

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
